# Uncomment the next line to define a global platform for your project
 platform :ios, '12.1'

target 'app-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app-ios

  pod 'tealium-swift'

#  target 'app-iosTests' do
 #   inherit! :search_paths
    # Pods for testing
 # end

  #target 'app-iosUITests' do
  #  inherit! :search_paths
    # Pods for testing
 # end

end
